LEXICON_DATA = [
    # Core academic roots
    {"root": "lip", "canonical_lemma": "lipa", "part_of_speech": "kitendo", "english_intent": "tuition_fees", "sample_surface_forms": ["kulipa", "inalipwa", "nimelipa", "unalipwaje", "utalipa"]},
    {"root": "ada", "canonical_lemma": "ada", "part_of_speech": "jina", "english_intent": "tuition_fees", "sample_surface_forms": ["ada", "yada"]},
    {"root": "sajil", "canonical_lemma": "sajili", "part_of_speech": "kitendo", "english_intent": "course_registration", "sample_surface_forms": ["kusajili", "nisiposajili", "usajili", "wamesajili"]},
    {"root": "tihani", "canonical_lemma": "mtihani", "part_of_speech": "jina", "english_intent": "exam_timetable", "sample_surface_forms": ["mtihani", "mitihani", "tahiniwa"]},
    {"root": "tahini", "canonical_lemma": "tahini", "part_of_speech": "kitendo", "english_intent": "exam_timetable", "sample_surface_forms": ["kutahiniwa", "walitahiniwa"]},
    {"root": "fuz", "canonical_lemma": "fuzu", "part_of_speech": "kitendo", "english_intent": "graduation_requirements", "sample_surface_forms": ["kufuzu", "uhitimu", "mahafali"]},
    {"root": "tambulisisho", "canonical_lemma": "kitambulisho", "part_of_speech": "jina", "english_intent": "student_id", "sample_surface_forms": ["kitambulisho", "vitambulisho"]},
    {"root": "tambua", "canonical_lemma": "kitambulisho", "part_of_speech": "jina", "english_intent": "student_id", "sample_surface_forms": ["kitambulisho", "vitambulisho"]},
    {"root": "kopa", "canonical_lemma": "mkopo", "part_of_speech": "jina", "english_intent": "student_loans", "sample_surface_forms": ["mkopo", "mikopo", "kuomba mkopo", "helb"]},
    {"root": "fadhil", "canonical_lemma": "ufadhili", "part_of_speech": "jina", "english_intent": "scholarships", "sample_surface_forms": ["bursary", "ufadhili", "fadhiliwa"]},
    {"root": "hamish", "canonical_lemma": "hamisha", "part_of_speech": "kitendo", "english_intent": "credit_transfer", "sample_surface_forms": ["kuhamisha", "uhamisho", "hamia"]},
    {"root": "ahirish", "canonical_lemma": "ahirisha", "part_of_speech": "kitendo", "english_intent": "deferment", "sample_surface_forms": ["kuahirisha", "ahirisho"]},
    {"root": "som", "canonical_lemma": "soma", "part_of_speech": "kitendo", "english_intent": "academics", "sample_surface_forms": ["soma", "ninasoma", "waliosoma", "masomo"]},
    {"root": "chumba", "canonical_lemma": "chumba", "part_of_speech": "jina", "english_intent": "hostel_allocation", "sample_surface_forms": ["chumba", "vyumba", "hostel"]},
    {"root": "maktaba", "canonical_lemma": "maktaba", "part_of_speech": "jina", "english_intent": "library_services", "sample_surface_forms": ["maktaba", "vitabu", "azima"]},
    {"root": "afya", "canonical_lemma": "afya", "part_of_speech": "jina", "english_intent": "health_services", "sample_surface_forms": ["afya", "zahanati", "hospitali"]},
    {"root": "kadi", "canonical_lemma": "kadi", "part_of_speech": "jina", "english_intent": "exam_card", "sample_surface_forms": ["kadi ya mtihani", "kadi"]},
    {"root": "cheti", "canonical_lemma": "cheti", "part_of_speech": "jina", "english_intent": "graduation_requirements", "sample_surface_forms": ["cheti", "vyeti", "shahada"]},
    {"root": "awamu", "canonical_lemma": "awamu", "part_of_speech": "jina", "english_intent": "tuition_fees", "sample_surface_forms": ["awamu", "magawio"]},
    {"root": "ratiba", "canonical_lemma": "ratiba", "part_of_speech": "jina", "english_intent": "exam_timetable", "sample_surface_forms": ["ratiba", "ratiba ya mitihani"]},
    {"root": "adhabu", "canonical_lemma": "adhabu", "part_of_speech": "jina", "english_intent": "disciplinary_policy", "sample_surface_forms": ["adhabu", "nidhamu"]},
    {"root": "poteza", "canonical_lemma": "poteza", "part_of_speech": "kitendo", "english_intent": "student_id", "sample_surface_forms": ["poteza", "nimepoteza", "kupotea"]},
    {"root": "pata", "canonical_lemma": "pata", "part_of_speech": "kitendo", "english_intent": "academics", "sample_surface_forms": ["kupata", "napataje"]},
    {"root": "wez", "canonical_lemma": "weza", "part_of_speech": "kitendo", "english_intent": "academics", "sample_surface_forms": ["ninawezaje", "anaweza"]},
    {"root": "omba", "canonical_lemma": "omba", "part_of_speech": "kitendo", "english_intent": "scholarships", "sample_surface_forms": ["kuomba", "maombi"]},
    {"root": "bursary", "canonical_lemma": "bursary", "part_of_speech": "jina", "english_intent": "scholarships", "sample_surface_forms": ["bursary"]},
    {"root": "helb", "canonical_lemma": "helb", "part_of_speech": "jina", "english_intent": "student_loans", "sample_surface_forms": ["helb", "mikopo ya elimu"]},
    {"root": "kitengo", "canonical_lemma": "kitengo", "part_of_speech": "jina", "english_intent": "course_registration", "sample_surface_forms": ["kitengo", "vitengo", "kozi"]},
    {"root": "kozi", "canonical_lemma": "kozi", "part_of_speech": "jina", "english_intent": "course_registration", "sample_surface_forms": ["kozi", "masomo"]},
    {"root": "transkripti", "canonical_lemma": "transkripti", "part_of_speech": "jina", "english_intent": "transcripts_request", "sample_surface_forms": ["transkripti", "matokeo"]},
    {"root": "matokeo", "canonical_lemma": "matokeo", "part_of_speech": "jina", "english_intent": "transcripts_request", "sample_surface_forms": ["matokeo", "alama"]},
    {"root": "kazi", "canonical_lemma": "kazi", "part_of_speech": "jina", "english_intent": "work_study", "sample_surface_forms": ["kazi", "kazi za kampasi"]},
    {"root": "uchaguzi", "canonical_lemma": "uchaguzi", "part_of_speech": "jina", "english_intent": "student_elections", "sample_surface_forms": ["uchaguzi", "kusa", "kiongozi"]},
    {"root": "mtandao", "canonical_lemma": "mtandao", "part_of_speech": "jina", "english_intent": "ict_portal", "sample_surface_forms": ["mtandao", "wifi", "portal", "nywila"]},
    {"root": "nywila", "canonical_lemma": "nywila", "part_of_speech": "jina", "english_intent": "ict_portal", "sample_surface_forms": ["nywila", "password"]},
    {"root": "michezo", "canonical_lemma": "michezo", "part_of_speech": "jina", "english_intent": "sports_recreation", "sample_surface_forms": ["michezo", "uwanja", "gym"]},
    {"root": "uwanja", "canonical_lemma": "uwanja", "part_of_speech": "jina", "english_intent": "sports_recreation", "sample_surface_forms": ["uwanja", "michezo"]},
    {"root": "chakula", "canonical_lemma": "chakula", "part_of_speech": "jina", "english_intent": "catering_services", "sample_surface_forms": ["chakula", "mlo", "cafeteria"]},
    {"root": "mlo", "canonical_lemma": "mlo", "part_of_speech": "jina", "english_intent": "catering_services", "sample_surface_forms": ["mlo", "milolize"]},
    {"root": "visa", "canonical_lemma": "visa", "part_of_speech": "jina", "english_intent": "international_students", "sample_surface_forms": ["visa", "pasi", "watafiti"]},
    {"root": "utafiti", "canonical_lemma": "utafiti", "part_of_speech": "jina", "english_intent": "research_ethics", "sample_surface_forms": ["utafiti", "tasnifu"]},
    {"root": "usalama", "canonical_lemma": "usalama", "part_of_speech": "jina", "english_intent": "security_emergency", "sample_surface_forms": ["usalama", "dharura", "polisi"]},
    {"root": "dharura", "canonical_lemma": "dharura", "part_of_speech": "jina", "english_intent": "security_emergency", "sample_surface_forms": ["dharura", "ripoti"]},
    {"root": "attachment", "canonical_lemma": "attachment", "part_of_speech": "jina", "english_intent": "industrial_attachment", "sample_surface_forms": ["attachment", "mafunzo ya nyanjani"]},
    {"root": "nyanjani", "canonical_lemma": "nyanjani", "part_of_speech": "jina", "english_intent": "industrial_attachment", "sample_surface_forms": ["nyanjani", "mafunzo"]},
    {"root": "muhula", "canonical_lemma": "muhula", "part_of_speech": "jina", "english_intent": "tuition_fees", "sample_surface_forms": ["muhula", "semester"]},
    {"root": "likizo", "canonical_lemma": "likizo", "part_of_speech": "jina", "english_intent": "deferment", "sample_surface_forms": ["likizo", "likizo ya masomo"]},
    {"root": "kusafisha", "canonical_lemma": "kusafisha", "part_of_speech": "kitendo", "english_intent": "graduation_requirements", "sample_surface_forms": ["clearance", "kusafisha", "uhakiki"]},
    {"root": "clearance", "canonical_lemma": "clearance", "part_of_speech": "jina", "english_intent": "graduation_requirements", "sample_surface_forms": ["clearance", "uhakiki"]},
    {"root": "vitengo", "canonical_lemma": "vitengo", "part_of_speech": "jina", "english_intent": "course_registration", "sample_surface_forms": ["vitengo", "units"]},
    {"root": "units", "canonical_lemma": "units", "part_of_speech": "jina", "english_intent": "course_registration", "sample_surface_forms": ["units", "vitengo"]}
]
